//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Pia_Estructura.rc
//
#define IDD_LOGIN                       100
#define IDD_MEDICOS                     101
#define IDD_CONSULTORIOS                103
#define IDD_ESPECIALIDADES              105
#define IDD_PACIENTES                   107
#define IDD_REPORTE_CONSULTA_MEDICO     109
#define IDD_REPORTE_CITAS_PACIENTE      111
#define IDD_MENU                        113
#define IDD_CITAS_MEDICAS               117
#define IDD_REGISTRO                    121
#define LB_MEDICOS                      1001
#define BT_AGREGAR_MEDICO               1002
#define BT_MODIFICAR_MEDICO             1003
#define BT_ELIMINAR_MEDICO              1004
#define EC_NUM_CEDULA_MEDICO            1005
#define EC_NOMBRE_MEDICO                1006
#define EC_CORREO_MEDICO                1007
#define EC_TELEFONO_MEDICO              1008
#define CB_ESPECIALIDAD_MEDICO          1009
#define CB_CANTIDAD_CONSULTORIOS        1012
#define CB_DIAS_CONSULTORIOS            1013
#define CB_HORARIOS_CONSULTORIOS        1014
#define CB_HORA_INICIO                  1014
#define BT_AGREGAR_CONSULTORIO          1015
#define BT_SALIR_CONSULTORIOS           1016
#define LB_ESPECIALIDADES               1017
#define EC_AGREGAR_ESPECIALIDAD         1018
#define BT_AGREGAR_ESPECIALIDAD         1019
#define BT_SALIR_ESPECIALIDAD           1020
#define LB_PACIENTES                    1021
#define BT_AGREGAR_PACIENTES            1022
#define BT_MODIFICAR_PACIENTES          1023
#define BT_ELIMINAR_PACIENTES           1024
#define BT_SALIR_MEDICOS                1025
#define EC_ID_PACIENTE                  1026
#define EC_NOMBRE_PACIENTE              1027
#define EC_CORREO_PACIENTE              1028
#define EC_TELEFONO_PACIENTE            1029
#define EC_EDAD_PACIENTE                1032
#define BT_CONFIRMAR_PACIENTE           1033
#define BT_SALIR_PACIENTE               1034
#define CB_ESPECIALIDAD_REPCONSMEDICO   1035
#define BT_CONFIRMAR_REPCONSMEDICO      1036
#define LB_REPCONSMEDICO                1037
#define CB_FECHAINICIAL_REPCONSMEDICO   1039
#define CB_FECHAFINAL_REPCONSMEDICO     1040
#define EC_CEDULA_REPCONSMEDICO         1041
#define EC_NOMBRE_REPCONSMEDICO         1042
#define DT_FECHA_REPCONSMEDICO          1043
#define EC_HORA_REPCONSMEDICO           1044
#define EC_PACIENTE_REPCONSMEDICO       1045
#define EC_DIAGNOSTICO_REPCONSMEDICO    1046
#define EC_ESTATUS_REPCONSMEDICO        1048
#define BT_SALIR_REPCONSMEDICO          1049
#define BT_CONFIRMAR_REPCITASPACIENTE   1053
#define LB_REPCITASPACIENTE             1054
#define EC_ID_REPCITASPACIENTE          1055
#define EC_NOMBREPACIENTE_REPCITASPACIENTE 1056
#define DT_FECHA_REPCITASPACIENTE       1057
#define EC_HORA_REPCITASPACIENTE        1058
#define EC_NOMBREMEDICO_REPCITASPACIENTE 1059
#define EC_ESPECIALIDAD_REPCITASPACIENTE 1060
#define EC_ESTATUS_REPCITASPACIENTE     1061
#define EC_DIAGNOSTICO_REPCITASPACIENTE 1062
#define BT_SALIR_REPCITASPACIENTE       1063
#define BT_MEDICOS_MENU                 1064
#define BT_PACIENTES_MENU               1065
#define BT_CONSULTORIOS_MENU            1066
#define BT_ESPECIALIDADES_MENU          1067
#define BT_REPCITASPACIENTE_MENU        1068
#define BT_REPCONSULTAMEDICO_MENU       1069
#define CB_GENERO_PACIENTE              1070
#define BT_ELIMINAR_ESPECIALIDAD        1071
#define CB_HORA_FIN                     1072
#define BT_ELIMINAR_CONSULTORIO         1073
#define LB_CONSULTORIOS                 1074
#define CB_PACIENTE_CITA                1075
#define CB_ESPECIALIDAD_CITA            1076
#define CB_MEDICO_CITA                  1077
#define DT_FECHA_CITA                   1078
#define CB_HORA_CITA                    1079
#define LB_CITAS                        1080
#define EC_DIAGNOSTICO_CITA             1082
#define BT_SALIR_CITA                   1083
#define BT_GUARDAR_DIAGNOSTICO          1084
#define BT_AGREGAR_CITA                 1085
#define BT_CANCELAR_CITA                1086
#define BT_CONFIRMAR_CITA               1087
#define BT_CITAS_MEDICAS_MENU           1088
#define BT_SALIR_MENU                   1089
#define BT_ORDENAR_MEDICOS              1090
#define BT_ORDENAR_PACIENTES            1091
#define BT_ORDENAR_ESPECIALIDAD         1092
#define BT_ORDENAR_CONSULTORIOS         1094
#define BT_ORDENAR_CITAS_ESTADO         1095
#define EC_DIA_REPCONSMEDICO            1096
#define DT_FECHAFINAL_REPCONSMEDICO     1097
#define DT_FECHAINICIAL_REPCONSMEDICO   1098
#define EC_FECHA_REPCONSMEDICO          1099
#define DT_FECHAINICIAL_REPCITASPACIENTE 1102
#define DT_FECHAFINAL_REPCITASPACIENTE  1103
#define EC_FECHA_REPCITASPACIENTE       1104
#define EC_DIA_REPCITASPACIENTE         1106
#define EC_APELLIDOP_PACIENTE           1107
#define EC_APELLIDOM_PACIENTE           1108
#define EC_APELLIDOP_MEDICO             1109
#define EC_APELLIDOM_MEDICO             1110
#define LB_CITAS_REPCONSMEDICO          1111
#define LB_CITAS_REPPACIENTE            1112
#define EC_BUSCAR_APELLIDO_PACIENTE     1113
#define BT_BUSCAR_APELLIDO_PACIENTE     1114
#define EC_USUARIO_LOGIN                1115
#define EC_PASSWORD_LOGIN               1118
#define BT_INGRESAR_LOGIN               1119
#define BT_SALIR_LOGIN                  1120
#define BT_REGISTRARSE_LOGIN            1121
#define EC_USUARIO_REGISTRO             1122
#define EC_PASSWORD_REGISTRO            1123
#define EC_CONFIRMAR_PASSWORD_REGISTRO  1124
#define BT_CREAR_USUARIO                1125
#define BT_CANCELAR_REGISTRO            1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
